{% set version = '0.4.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggjoy
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggjoy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggjoy/ggjoy_{{ version }}.tar.gz
  sha256: d2f778bc40203d7fbb7c81b40beed8614c36ea10448e911663cc6109aa685504

build:
  merge_build_host: True  # [win]
  number: 1004
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-ggridges >=0.4.0
  run:
    - r-base
    - r-ggplot2
    - r-ggridges >=0.4.0

test:
  commands:
    - $R -e "library('ggjoy')"           # [not win]
    - "\"%R%\" -e \"library('ggjoy')\""  # [win]

about:
  home: https://github.com/clauswilke/ggjoy
  license: GPL-2.0-only
  summary: Joyplots provide a convenient way of visualizing changes in distributions over time
    or space. This package enables the creation of such plots in 'ggplot2'.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
