travis:
  secure:
    BINSTAR_TOKEN: C1nfoKDjbagd2wuBNjtsPbPuMTej20B96y727so4ZoMgRNrworsvnFKugrceON+LvPQqaHlkhof7Clz8XDTcJ6NXQGizJ29wXWf3DOxa4hcoHzw/1s+rCYAMX869rVqK9fXCZWZhQ8RlIey0YLUcA9yKGKYry9Cl6OAYW5oQvAKGbpUOOf194AwoonFA0XIgC6nQhdPTVkl7FSNK0POe/w7yk0yVx8hQhzB8o3dJQJmuw+o/kEBG9hlT7WVTZ8aUIvaPMk8VKE3OsV3//Z0DGW/oqMtA4Q2+s0ETmBy5JU8SKqDr647yygL9E2ADGhZYQWnWHXFYtg926vmTN75yozmgjrF74o5Ja7FEze8FI7O4whkq2/z7ZW6bWCqCuIafe5TXxxvIbdAFsKT57DFGmvB1u5hyssqFPSrHoy+eRyVaJ1SbvCnaKIssaoFZZYMu20sO/7lXZbNFxXI7OiSTsas2Fn1wOjE4XCl/pv2Fa+QLtk8aapxzoifTX6y1W7Fy5Y4yiaJjN0BfNohctkS578+8FjKoCkp0Syhq3HUB4sdw/YzyV7QLz8M2/KlXfKEczPkVzUnQD6aRE3SgsF7EJTuxEoSyB2opVyFlGJ4920+Xsu1BiD2RxchLXCc3ZtBpZPosXrpV7v485FBWfGd+VUlSGiSFU9vwZGeTLIlOiCk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
