travis:
  secure:
    BINSTAR_TOKEN: AgPJv93V9O34F/sCkKfTVqhkUzEQYhiKiKVImVQdJUNuQ/AU8A+4snOEwG+HXYfj6zAaEZF7Uy86GhAGTn73spfCcfJZ0fqkYXHvrKs4qONNK8T3FPbVVnt8CyI3/bdUgaz530xlEjboWWcXmGI3JEipxANRa5HqDAx0fSF6mbTVq+uzfwRdQzLrU7QECXs6dP7BmO21szI+2HvZg2q1yyRmdTPG+ziRLEpA6GilWRCYibTGefPVNWk8BcUyvtQcmGFjdIuWQybTuIjQLx+1b4ZGblCJI0Uyrmdzee7d/MOgSQmTIfjOy+1Ux+eg0CBVssAIno+cp6lu8YewqL8uXb8WzqTlWnCWU0WTfxPRCwUZC5EkMLvEIb/GIEBwZ0e/8QzS7UKCkepwumv4eZNjEqDe7wf4Ob3Uub/prUkUeH72Z1H5LEYUNkilYqxbMRMGKhq6GF0GM1IhSTQYtAa/ZKSqIZNFJp1ulcYDbgaiQe/5Yx2v30p2FHK9UcInGb23zI5Rm5pr3r8i4ZhJA7DpMN+pGsqOZcrr/RZrW790EUAV3oaVK+LRhZ4TzWVXgUigMkga+gmKRhWUKvq1hFWZBoG2s8Sg/jwILaQOypXSjq60lpYmNoPDEJZG/J974+s0p6HsBTT78hTaqKHNWlwAqU7XQk4YZnyGVlYo+zwBf1M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
